logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
azure:
  activedirectory:
    client-id: 87fe78e0-ad84-42cf-a55e-309e110e40e8
    client-secret: 7nLmy2s.5Pv3-hEXvMbQtg-~5V3_Z0E6VK
    tenant-id: 36e902d6-0a6f-4ec9-9067-297246dd99f8
    authorization-clients:
      facility-request:
        scopes: openid, profile, offline_access, api://facility-inventory/Facility.Read, api://facility-inventory/Facility.Write
server:
  port: 8880

facility-inventory-base-url: ${FACILITY_INVENTORY_BASE_URL:http://localhost:8881}
