azure:
  activedirectory:
    tenant-id: 36e902d6-0a6f-4ec9-9067-297246dd99f8
    client-id: b7d58b57-a71f-4115-b501-fa84647200a6
    client-secret: S-a18kTmeCFE0b2S_wtf9.psA.q7PhtkQ~
    app-id-uri: api://facility-inventory
    authorization-clients:
      facility-inventory:
        authorization-grant-type: on_behalf_of
        scopes: api://hr/HealthInformation:Read

server:
  port: 8881

hr-base-url: ${HR_BASE_URL:http://localhost:8882}
