spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/36e902d6-0a6f-4ec9-9067-297246dd99f8/

server:
  port: 8882

logging:
  level:
    org.springframework.security: TRACE
